### ISSUE TITLE
Vertex adjacency Corresponds to Edge Length?

### ISSUE THREAD

**Issue by sotha-sil-zen** [kentechx/hole-filling#2]
https://github.com/kentechx/HoleFillingPy/blob/0444c0bf445036bdca703b338c4d5fd4d100b88e/main.py#L178
I'm not sure whether this broadcasting is appropriate since "vertex adjacency" and  "edge length of facets" do not share the same size.

**Comment by kentechx** [comment]
Thanks for your feedback, this is fixed.
